---
- hosts: 172.31.9.186
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
      name: apache2

  - name: i want to copy static file to ansible nodes
    copy: 
      src: static.txt
      dest: /home/ubuntu/static.txt

  - name: i want to copy dynamic file to ansible nodes
    template: 
      src: dynofile.j2
      dest: /home/ubuntu/static.txt    

  - name: i want to download remote into ansible nodes
    get_url:
      url: https://updates.jenkins.io/download/war/2.380/jenkins.war 
      dest: /home/ubuntu/jenkins.war
          
      



