---
- hosts: mywebservers
  become: yes
  tasks: 
  -  name: webserver on ubuntu
     apt: 
       name: "{{mywebpackonubuntu}}"
       state: present
     when: ansible_os_family =="Debian"

  -  name: start webserver on ubuntu
     service: 
       name: "{{mywebpackonubuntu}}"
       state: started
     when: ansible_os_family =="Debian"

  -  name: install httpd on RedHat
     yum: 
       name: "{{mywebpackonredhat}}"
       state: present
     when: ansible_os_family =="RedHat"

  -  name: start httpd on RedHat
     service: 
       name: "{{mywebpackonredhat}}"
       state: started
     when: ansible_os_family =="RedHat"


      
       

       