---
- hosts: all
  become: yes
  tasks:
  - name: Install webserver on ubuntu  
    ansible.builtin.apt:
      name: apache2
      state: present
    When: ansible_OS _family == "Debian" 

  - name: Start apache httpd  
    ansible.builtin.service:
      name: apache2
      state: started
    When: ansible_OS_family == "Debian"  

  - name: Install webserver on RedHat  
    ansible.builtin.apt:
      name: apache2
      state: present
    When: ansible_OS_family == "RedHat"

  - name: Start webserver on RedHat
    ansible.builtin.service:
      name: apache2
      state: started    
    When: ansible_OS_family == "RedHat""
        
